# NumPy Tutorial

## Load in NumPy

In [111]:
import numpy as np

## The Basics

In [112]:
a = np.array([1, 2, 3])

print(a)

[1 2 3]


In [113]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])

print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


## Get the Dimension

In [114]:
a.ndim

1

In [115]:
b.ndim

2

In [116]:
a.shape

(3,)

In [117]:
b.shape

(2, 3)

In [118]:
# Get type
a.dtype

dtype('int64')

In [119]:
b.dtype

dtype('float64')

In [120]:
# Change the data type
a_new = np.array([1, 2, 3], dtype='int16')

a_new

array([1, 2, 3], dtype=int16)

In [121]:
a_new.dtype

dtype('int16')

In [122]:
# Get size
a.itemsize

8

In [123]:
b.itemsize

8

In [124]:
a_new.itemsize

2

In [125]:
# Get total size
a.size

3

In [126]:
b.size

6

In [127]:
a.nbytes

24

In [128]:
a_new.nbytes

6

In [129]:
b.nbytes

48

## Accessing/Changing specific elements, rows, columns

In [130]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [131]:
# Get a specific element [r, c]
a[1, 5]

13

In [132]:
a[1, -2]

13

In [133]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [134]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [135]:
# Get a little bit more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [136]:
# Change a specific element
a[1, 5] = 20

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [137]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [138]:
a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-D example

In [139]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [140]:
# Get specific element (work outside in)
b[0, 1, 1]

4

In [141]:
# Replace
b[:, 1, :]

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [142]:
# Replace
b[:, 1, :] = [[9, 9], [8, 8]]

print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initialising Different Types of Arrays

In [143]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [144]:
# All 1s matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [145]:
# Any other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [146]:
# Any other number
np.full((2, 2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [147]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [148]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.88829014, 0.40366676],
       [0.83410068, 0.34333999],
       [0.37447834, 0.26613323],
       [0.24156235, 0.25968962]])

In [149]:
np.random.rand(4, 2, 3)

array([[[0.97904476, 0.50376963, 0.74996164],
        [0.93635869, 0.8813072 , 0.6673602 ]],

       [[0.28282981, 0.74952131, 0.10519934],
        [0.80390675, 0.77148965, 0.90611466]],

       [[0.90679049, 0.91810198, 0.84053723],
        [0.09681299, 0.7017215 , 0.46096044]],

       [[0.07928201, 0.37514972, 0.37190206],
        [0.77977548, 0.13667986, 0.14837296]]])

In [150]:
np.random.random_sample(a.shape)

array([[0.56638192, 0.15674084, 0.58353998, 0.60870175, 0.27831434,
        0.63414171, 0.27189325],
       [0.10359277, 0.02870937, 0.05657458, 0.95331735, 0.00501814,
        0.8578308 , 0.48557861]])

In [151]:
# Random integer values
np.random.randint(7)

5

In [152]:
np.random.randint(7, size=(3, 3))

array([[2, 2, 0],
       [5, 6, 3],
       [6, 2, 2]])

In [153]:
np.random.randint(-4, 8, size=(3, 3))

array([[ 2, -2,  5],
       [ 2, -3,  2],
       [ 5,  5, -2]])

In [154]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [155]:
# Repeat an array
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [156]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [157]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [158]:
# Create a pattern array
output = np.ones((5, 5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [159]:
z = np.zeros((3, 3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [160]:
z[1, 1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [161]:
# output[1:4, 1:4] = z
output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays

In [162]:
a = np.array([1, 2, 3])
print(a)
b = a
print(b)
b[0] = 100
print(a)

[1 2 3]
[1 2 3]
[100   2   3]


In [163]:
a = np.array([1, 2, 3])
print(a)
b = a.copy()
print(b)
b[0] = 100
print(a)
print(b)

[1 2 3]
[1 2 3]
[1 2 3]
[100   2   3]


### Mathematics

In [164]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [165]:
a + 2

array([3, 4, 5, 6])

In [166]:
a - 2

array([-1,  0,  1,  2])

In [167]:
a * 2

array([2, 4, 6, 8])

In [168]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [169]:
b = np.array([1, 0, 1, 0])
b

array([1, 0, 1, 0])

In [170]:
a + b

array([2, 2, 4, 4])

In [171]:
a ** 2

array([ 1,  4,  9, 16])

In [172]:
# Take the sine of the elements
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [173]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear Algebra

In [174]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [175]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [176]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [177]:
np.min(stats)

1

In [178]:
np.min(stats, axis=1)

array([1, 4])

In [179]:
np.min(stats, axis=0)

array([1, 2, 3])

In [180]:
np.max(stats)

6

In [181]:
np.max(stats, axis=1)

array([3, 6])

In [182]:
np.sum(stats)

21

In [183]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [184]:
np.sum(stats, axis=1)

array([ 6, 15])

## Reorganising Arrays

In [185]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)
print(before.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [186]:
after = before.reshape((8, 1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [187]:
after = before.reshape((4, 2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [188]:
after = before.reshape((2, 2, 2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [189]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [190]:
np.vstack([v1, v2, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [191]:
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [192]:
# Horizontally stacking vectors
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
print(h1)
print(h2)

np.hstack((h1, h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

### Load data from file

In [193]:
filedata = np.genfromtxt('data-orig.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [194]:
filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

### Boolean masking and advanced indexing

In [195]:
# One can index with a list in numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [196]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [197]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [198]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [199]:
np.any(filedata > 50, axis=1)

array([ True,  True,  True])

In [200]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [201]:
np.all(filedata > 50, axis=1)

array([False, False, False])

In [202]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [203]:
~((filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

## Exercises

In [204]:
test_matrix = np.arange(1, 31).reshape((6, 5))
test_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [205]:
sub_matrix01 = test_matrix[2:4, 0:2]
sub_matrix01

array([[11, 12],
       [16, 17]])

In [206]:
sub_matrix02 = test_matrix[[0, 1, 2, 3], [1, 2, 3, 4]]
sub_matrix02

array([ 2,  8, 14, 20])

In [207]:
sub_matrix03 = [test_matrix[0:1, 3:5], test_matrix[4:6, 3:5]]
sub_matrix03

[array([[4, 5]]),
 array([[24, 25],
        [29, 30]])]

In [210]:
sub_matrix04 = np.vstack([test_matrix[0:1, 3:5], test_matrix[4:6, 3:5]])
sub_matrix04

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [212]:
sub_matrix05 = test_matrix[[0, 4, 5], 3:]
sub_matrix05

array([[ 4,  5],
       [24, 25],
       [29, 30]])