# NumPy Tutorial

## Load in NumPy

In [2]:
import numpy as np

## The Basics

In [3]:
a = np.array([1, 2, 3])

print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])

print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


## Get the Dimension

In [5]:
a.ndim

1

In [6]:
b.ndim

2

In [7]:
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [9]:
# Get type
a.dtype

dtype('int64')

In [10]:
b.dtype

dtype('float64')

In [11]:
# Change the data type
a_new = np.array([1, 2, 3], dtype='int16')

a_new

array([1, 2, 3], dtype=int16)

In [12]:
a_new.dtype

dtype('int16')

In [13]:
# Get size
a.itemsize

8

In [14]:
b.itemsize

8

In [15]:
a_new.itemsize

2

In [16]:
# Get total size
a.size

3

In [17]:
b.size

6

In [18]:
a.nbytes

24

In [19]:
a_new.nbytes

6

In [20]:
b.nbytes

48

## Accessing/Changing specific elements, rows, columns

In [21]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [22]:
# Get a specific element [r, c]
a[1, 5]

13

In [23]:
a[1, -2]

13

In [24]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [26]:
# Get a little bit more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [27]:
# Change a specific element
a[1, 5] = 20

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [28]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [29]:
a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-D example

In [30]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
# Get specific element (work outside in)
b[0, 1, 1]

4

In [32]:
# Replace
b[:, 1, :]

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [33]:
# Replace
b[:, 1, :] = [[9, 9], [8, 8]]

print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initialising Different Types of Arrays

In [34]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
# All 1s matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [36]:
# Any other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [37]:
# Any other number
np.full((2, 2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [38]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [39]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.45830212, 0.24759308],
       [0.51363066, 0.88826299],
       [0.72807043, 0.16624369],
       [0.22120417, 0.10788782]])

In [40]:
np.random.rand(4, 2, 3)

array([[[0.15551423, 0.64471338, 0.21947813],
        [0.19600831, 0.8720961 , 0.30311456]],

       [[0.29244481, 0.61471171, 0.35634201],
        [0.12495922, 0.680394  , 0.53119405]],

       [[0.99433049, 0.13802287, 0.57947434],
        [0.21962293, 0.45471714, 0.41012103]],

       [[0.32247836, 0.55127019, 0.76367994],
        [0.37949965, 0.1044912 , 0.02298334]]])

In [41]:
np.random.random_sample(a.shape)

array([[0.19022973, 0.39777814, 0.23956677, 0.33837314, 0.22150985,
        0.82572279, 0.88092074],
       [0.68261408, 0.30575138, 0.82427912, 0.53696591, 0.463158  ,
        0.42579378, 0.81601643]])

In [42]:
# Random integer values
np.random.randint(7)

6

In [43]:
np.random.randint(7, size=(3, 3))

array([[3, 2, 5],
       [4, 5, 0],
       [3, 0, 3]])

In [44]:
np.random.randint(-4, 8, size=(3, 3))

array([[-3,  3,  2],
       [ 3,  6, -2],
       [ 6,  2, -1]])

In [45]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
# Repeat an array
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [47]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [48]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [49]:
# Create a pattern array
output = np.ones((5, 5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [50]:
z = np.zeros((3, 3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [51]:
z[1, 1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [52]:
# output[1:4, 1:4] = z
output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays

In [53]:
a = np.array([1, 2, 3])
print(a)
b = a
print(b)
b[0] = 100
print(a)

[1 2 3]
[1 2 3]
[100   2   3]


In [54]:
a = np.array([1, 2, 3])
print(a)
b = a.copy()
print(b)
b[0] = 100
print(a)
print(b)

[1 2 3]
[1 2 3]
[1 2 3]
[100   2   3]


### Mathematics

In [55]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [56]:
a + 2

array([3, 4, 5, 6])

In [57]:
a - 2

array([-1,  0,  1,  2])

In [58]:
a * 2

array([2, 4, 6, 8])

In [59]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [60]:
b = np.array([1, 0, 1, 0])
b

array([1, 0, 1, 0])

In [61]:
a + b

array([2, 2, 4, 4])

In [62]:
a ** 2

array([ 1,  4,  9, 16])

In [63]:
# Take the sine of the elements
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [64]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear Algebra

In [65]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [66]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [67]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.min(stats)

1

In [70]:
np.min(stats, axis=1)

array([1, 4])

In [72]:
np.min(stats, axis=0)

array([1, 2, 3])

In [73]:
np.max(stats)

6

In [74]:
np.max(stats, axis=1)

array([3, 6])

In [75]:
np.sum(stats)

21

In [76]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [77]:
np.sum(stats, axis=1)

array([ 6, 15])

## Reorganising Arrays

In [81]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)
print(before.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [82]:
after = before.reshape((8, 1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [83]:
after = before.reshape((4, 2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [84]:
after = before.reshape((2, 2, 2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
