# NumPy Tutorial

## Load in NumPy

In [2]:
import numpy as np

## The Basics

In [3]:
a = np.array([1, 2, 3])

print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])

print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


## Get the Dimension

In [5]:
a.ndim

1

In [6]:
b.ndim

2

In [7]:
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [9]:
# Get type
a.dtype

dtype('int64')

In [10]:
b.dtype

dtype('float64')

In [11]:
# Change the data type
a_new = np.array([1, 2, 3], dtype='int16')

a_new

array([1, 2, 3], dtype=int16)

In [12]:
a_new.dtype

dtype('int16')

In [15]:
# Get size
a.itemsize

8

In [17]:
b.itemsize

8

In [18]:
a_new.itemsize

2

In [19]:
# Get total size
a.size

3

In [20]:
b.size

6

In [21]:
a.nbytes

24

In [22]:
a_new.nbytes

6

In [23]:
b.nbytes

48

## Accessing/Changing specific elements, rows, columns

In [25]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
# Get a specific element [r, c]
a[1, 5]

13

In [27]:
a[1, -2]

13

In [28]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [30]:
# Get a little bit more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [32]:
# Change a specific element
a[1, 5] = 20

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [33]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [34]:
a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-D example

In [35]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
# Get specific element (work outside in)
b[0, 1, 1]

4

In [37]:
# Replace
b[:, 1, :]

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
# Replace
b[:, 1, :] = [[9, 9], [8, 8]]

print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initialising Different Types of Arrays

In [39]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
# All 1s matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [41]:
# Any other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [42]:
# Any other number
np.full((2, 2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [43]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [44]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.9294122 , 0.28252307],
       [0.74972518, 0.20452202],
       [0.09906697, 0.81611751],
       [0.36831007, 0.48101841]])

In [45]:
np.random.rand(4, 2, 3)

array([[[0.24704588, 0.18941886, 0.45742797],
        [0.84996517, 0.25170361, 0.54192657]],

       [[0.506796  , 0.35048401, 0.11468624],
        [0.26478025, 0.60974044, 0.35035735]],

       [[0.59639526, 0.92024137, 0.15106136],
        [0.74575319, 0.64259599, 0.44354304]],

       [[0.3267021 , 0.71010191, 0.39989229],
        [0.03387808, 0.22692171, 0.06068701]]])

In [46]:
np.random.random_sample(a.shape)

array([[0.78846102, 0.92434689, 0.65017575, 0.39718919, 0.79744867,
        0.5669164 , 0.15584018],
       [0.37339092, 0.89896428, 0.46314526, 0.84897997, 0.0321493 ,
        0.56902882, 0.92110079]])

In [47]:
# Random integer values
np.random.randint(7)

6

In [48]:
np.random.randint(7, size=(3, 3))

array([[1, 1, 5],
       [1, 0, 2],
       [5, 1, 0]])

In [50]:
np.random.randint(-4, 8, size=(3, 3))

array([[ 4,  7,  1],
       [-2,  6,  5],
       [-1,  1, -1]])

In [52]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
# Repeat an array
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [54]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [55]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [58]:
# Create a pattern array
output = np.ones((5, 5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [59]:
z = np.zeros((3, 3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [60]:
z[1, 1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [61]:
# output[1:4, 1:4] = z
output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays

In [62]:
a = np.array([1, 2, 3])
print(a)
b = a
print(b)
b[0] = 100
print(a)

[1 2 3]
[1 2 3]
[100   2   3]


In [63]:
a = np.array([1, 2, 3])
print(a)
b = a.copy()
print(b)
b[0] = 100
print(a)
print(b)

[1 2 3]
[1 2 3]
[1 2 3]
[100   2   3]


### Mathematics

In [64]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [65]:
a + 2

array([3, 4, 5, 6])

In [66]:
a - 2

array([-1,  0,  1,  2])

In [67]:
a * 2

array([2, 4, 6, 8])

In [68]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [70]:
b = np.array([1, 0, 1, 0])
b

array([1, 0, 1, 0])

In [71]:
a + b

array([2, 2, 4, 4])

In [72]:
a ** 2

array([ 1,  4,  9, 16])

In [73]:
# Take the sine of the elements
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [74]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear Algebra

In [78]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [79]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0