## NumPy Array Basics

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


In [4]:
arr.ndim

1

In [5]:
arr.shape

(5,)

In [6]:
len(arr)

5

In [7]:
arr_2d = np.array([
    [10, 20, 30, 40, 50],
    [100, 200, 300, 400, 500]
])

print(arr_2d)

[[ 10  20  30  40  50]
 [100 200 300 400 500]]


In [8]:
arr_2d.ndim

2

In [9]:
arr_2d.shape

(2, 5)

In [10]:
len(arr_2d)

2

In [11]:
arr_2d.size

10

In [12]:
arr_2d.dtype

dtype('int64')

In [13]:
np.array([1, "hello", 2])

array(['1', 'hello', '2'], dtype='<U21')

In [15]:
foo = np.array([1, "hello", 2])

print(foo)

['1' 'hello' '2']


In [16]:
foo[0] = "a really really really long string"

In [17]:
print(foo)

['a really really reall' 'hello' '2']


In [18]:
np.array([
    [1, 2, 3, 4],
    [5.5, 6.6, 7.7, 8.8]
])

array([[1. , 2. , 3. , 4. ],
       [5.5, 6.6, 7.7, 8.8]])

In [19]:
np.array([
    [1, 2, 3, 4],
    [1, 2]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.