## Creating NumPy Arrays

In [1]:
import numpy as np

In [2]:
np.array(["a", "b", "c"])

array(['a', 'b', 'c'], dtype='<U1')

In [3]:
np.array([
    ["a", "b"],
    ["c", "d"],
    ["e", "f"]
])

array([['a', 'b'],
       ['c', 'd'],
       ['e', 'f']], dtype='<U1')

In [4]:
np.array([
    [
        ["a", "b"],
        ["c", "d"],
        ["e", "f"]
    ],
    [
        ["g", "h"],
        ["i", "j"],
        ["k", "l"]
    ]
])

array([[['a', 'b'],
        ['c', 'd'],
        ['e', 'f']],

       [['g', 'h'],
        ['i', 'j'],
        ['k', 'l']]], dtype='<U1')

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros([3, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.full([3, 5], "cat")

array([['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat']], dtype='<U3')

In [8]:
np.arange(1, 5, 1)

array([1, 2, 3, 4])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.random.randint(1, 7, (2, 3))

array([[6, 1, 1],
       [6, 3, 4]])