## Indexing 1D Arrays

In [1]:
import numpy as np

In [2]:
foo = np.array([10, 20, 30, 40, 50])
print(foo)

[10 20 30 40 50]


In [3]:
foo[1]

20

In [5]:
foo[1] = 99
print(foo)

[10 99 30 40 50]


In [6]:
foo[4]

50

In [7]:
foo[len(foo)-1]

50

In [8]:
foo[-1]

50

In [9]:
foo[99]

IndexError: index 99 is out of bounds for axis 0 with size 5

In [10]:
foo[[0, 1, 4]]

array([10, 99, 50])

In [11]:
foo[[0, 1, 0, 1]]

array([10, 99, 10, 99])

In [15]:
foo[np.zeros(3, dtype="int32")]

array([10, 10, 10])

In [17]:
foo[:2]

array([10, 99])

In [18]:
foo[2:]

array([30, 40, 50])

In [19]:
foo[::2]

array([10, 30, 50])

In [25]:
foo[[0, 1, 4]] = [100, 200, 400]
print(foo)

[100 200  30  40 400]


In [26]:
foo[[0, 1, 4]] = [1, 2]
print(foo)

ValueError: shape mismatch: value array of shape (2,) could not be broadcast to indexing result of shape (3,)

In [27]:
foo[[0, 1, 4]] = [1]
print(foo)

[ 1  1 30 40  1]
