## 2.5 Indexing Multidimensional Arrays

In [1]:
import numpy as np

In [2]:
bar = np.array([
    [5, 10, 15, 20],
    [25, 30, 35, 40],
    [45, 50, 55, 60],
])
print(bar)

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]


In [3]:
bar[1, 2]

35

In [4]:
bar[0]

array([ 5, 10, 15, 20])

In [5]:
bar[0, None]

array([[ 5, 10, 15, 20]])

In [6]:
bar[:1]

array([[ 5, 10, 15, 20]])

In [7]:
bar[1:3, [-2, -1]]

array([[35, 40],
       [55, 60]])

In [9]:
bar[0, 0] = -1
print(bar)

[[-1 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]


In [10]:
bar[1] = bar[2]
print(bar)

[[-1 10 15 20]
 [45 50 55 60]
 [45 50 55 60]]


In [11]:
bar[[0, 1, 2], [0, 1, 2]] = [0, 0, 0]
print(bar)

[[ 0 10 15 20]
 [45  0 55 60]
 [45 50  0 60]]


In [12]:
bar_4 = np.array([
    [5, 10, 15, 20],
    [25, 30, 35, 40],
    [45, 50, 55, 60],
    [65, 70, 75, 80]
])
print(bar_4)

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]
 [65 70 75 80]]


In [14]:
bar_4[[0, 1, 2, 3], [0, 1, 2, 3]] = [0, 0, 0, 0]
print(bar_4)

[[ 0 10 15 20]
 [25  0 35 40]
 [45 50  0 60]
 [65 70 75  0]]


In [15]:
zoo = np.array([
    [
        [10, 20],
        [30, 40],
        [50, 60],
    ],
    [
        [11, 12],
        [13, 14],
        [15, 16],
    ]
])
print(zoo)

[[[10 20]
  [30 40]
  [50 60]]

 [[11 12]
  [13 14]
  [15 16]]]


In [16]:
zoo[0,:,1] = 5
print(zoo)

[[[10  5]
  [30  5]
  [50  5]]

 [[11 12]
  [13 14]
  [15 16]]]
