## 2.6 Basic Math on Arrays

In [2]:
import numpy as np

In [3]:
foo = np.array([[4, 3], [1, 0]])
bar = np.array([[1, 2], [3, 4]])

In [4]:
print(foo)

[[4 3]
 [1 0]]


In [5]:
print(bar)

[[1 2]
 [3 4]]


In [6]:
foo + bar

array([[5, 5],
       [4, 4]])

In [7]:
foo - bar

array([[ 3,  1],
       [-2, -4]])

In [8]:
foo * bar

array([[4, 6],
       [3, 0]])

In [9]:
foo / bar

array([[4.        , 1.5       ],
       [0.33333333, 0.        ]])

In [10]:
foo @ bar

array([[13, 20],
       [ 1,  2]])

In [11]:
foo + np.full(shape = (2, 2), fill_value=5)

array([[9, 8],
       [6, 5]])

In [12]:
foo + 5

array([[9, 8],
       [6, 5]])