## 2.7 Challenge: High School Reunion

With your high school reunion fast approaching, you decide to get in shape and lose some weight . You record your weight every day for five weeks starting on a Monday.

In [1]:
import numpy as np

In [2]:
dailywts = 185 - np.arange(5*7) / 5
print(dailywts)

[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


Given these daily weights, build an array with your average weight per weekend.

In [14]:
dailywts_reshaped = dailywts.reshape(5, 7)
print(dailywts_reshaped)

[[185.  184.8 184.6 184.4 184.2 184.  183.8]
 [183.6 183.4 183.2 183.  182.8 182.6 182.4]
 [182.2 182.  181.8 181.6 181.4 181.2 181. ]
 [180.8 180.6 180.4 180.2 180.  179.8 179.6]
 [179.4 179.2 179.  178.8 178.6 178.4 178.2]]


In [16]:
weekly_mean_weight = np.mean(dailywts_reshaped, axis=1)
print(weekly_mean_weight)

[184.4 183.  181.6 180.2 178.8]


In [10]:
sat_weights = dailywts[5::7]

In [11]:
sun_weights = dailywts[6::7]

In [12]:
total_weight_per_weekend = sat_weights + sun_weights

In [13]:
avg_weekend_weight = total_weight_per_weekend / 2
print(avg_weekend_weight)

[183.9 182.5 181.1 179.7 178.3]
