# NumPy Broadcasting

## Broadcasting Rules

Suppose we want to add two arrays, A and B ...

1. Moving backwards from the last dimension of each array, check if their dimensions are compatible.

- Dimensions are compatible if they are equal or either of them is one

2. If all of A's dimensions are compatible with B's dimensions, or vice-versa, they are compatible arrays.

In [2]:
import numpy as np

In [3]:
np.random.seed(1234)
A = np.random.randint(low = 1, high = 10, size = (3, 4))
B = np.random.randint(low = 1, high = 10, size = (3, 1))

In [5]:
print(A)

[[4 7 6 5]
 [9 2 8 7]
 [9 1 6 1]]


In [7]:
print(B)

[[7]
 [3]
 [1]]


In [8]:
A + B

array([[11, 14, 13, 12],
       [12,  5, 11, 10],
       [10,  2,  7,  2]])