## 3.10 Challenge: Psycho Parent Problem

Eager to make your mark on the PTA, you decide the best way to hide eggs for the upcoming easter egg hunt is to use NumPy. You represent the field as a 10x10 array of 0s. Now your goal is to insert twenty random normal values at random (non-repeating) locations in the grid that tell you how much candy to hide at each spot and where.

In [2]:
import numpy as np

In [3]:
field = np.zeros(shape = (10, 10))
print(field)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [4]:
np.set_printoptions(linewidth=999)
generator = np.random.default_rng(1234)

In [5]:
# Number of candies in each egg
values = np.round(generator.normal(size = 20), 2)
print(values)

# Sample 20 locations randomly
locations = generator.choice(field.size, len(values), replace = False)
print(locations)

[-1.6   0.06  0.74  0.15  0.86  2.91 -1.48  0.95 -1.67  0.34 -0.51  1.32 -0.86  0.52 -1.27 -2.16  0.43  1.73  0.52 -1.  ]
[15 99 42 55 41  5  3 86 39 35 61 46 63 48 11 84 24 17  0 51]


In [6]:
# Unravel the field array with numpy.ravel, then select the needed locations and assign the candy values to those locations

# Note: ravel() does not modify the array nor generates a new array. It just returns a view
field.ravel()[locations] = values
print(field)

[[ 0.52  0.    0.   -1.48  0.    2.91  0.    0.    0.    0.  ]
 [ 0.   -1.27  0.    0.    0.   -1.6   0.    1.73  0.    0.  ]
 [ 0.    0.    0.    0.    0.43  0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.34  0.    0.    0.   -1.67]
 [ 0.    0.86  0.74  0.    0.    0.    1.32  0.    0.52  0.  ]
 [ 0.   -1.    0.    0.    0.    0.15  0.    0.    0.    0.  ]
 [ 0.   -0.51  0.   -0.86  0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.   -2.16  0.    0.95  0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.06]]
