# NumPy Broadcasting - More Intro

In [6]:
import numpy as np

np.random.seed(4321)

In [7]:
A1 = np.random.randint(low = 1, high = 10, size = (4, 4))
B1 = np.random.randint(low = 1, high = 10, size = (2, 1))

In [8]:
print(A1)

[[3 9 3 2]
 [8 6 3 5]
 [7 1 9 7]
 [6 4 2 2]]


In [9]:
print(B1)

[[7]
 [2]]


In [10]:
A1 + B1

ValueError: operands could not be broadcast together with shapes (4,4) (2,1) 

In [11]:
np.random.seed(1111)
A2 = np.random.randint(low = 1, high = 10, size = (3, 1, 4))
B2 = np.random.randint(low = 1, high = 10, size = (2, 1))

In [12]:
print(A2)

[[[8 6 2 3]]

 [[5 9 7 5]]

 [[9 7 3 7]]]


In [13]:
print(B2)

[[9]
 [4]]


In [14]:
A2 + B2

array([[[17, 15, 11, 12],
        [12, 10,  6,  7]],

       [[14, 18, 16, 14],
        [ 9, 13, 11,  9]],

       [[18, 16, 12, 16],
        [13, 11,  7, 11]]])

In [15]:
A = np.array([3, 11, 4, 5])
B = np.array([5, 0, 3])

In [16]:
print(A)

[ 3 11  4  5]


In [17]:
print(B)

[5 0 3]


In [18]:
C = A - B

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [19]:
C = A[:, np.newaxis] - B[np.newaxis, :]
print(C)

[[-2  3  0]
 [ 6 11  8]
 [-1  4  1]
 [ 0  5  2]]


In [20]:
C_alt = A[:, None] - B[None, :]
print(C_alt)

[[-2  3  0]
 [ 6 11  8]
 [-1  4  1]
 [ 0  5  2]]
