# 3.3 NumPy Reshape

In [2]:
import numpy as np

In [3]:
foo = np.arange(1, 9)
print(foo)

[1 2 3 4 5 6 7 8]


In [4]:
foo.reshape(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
np.reshape(a = foo, newshape = (2, 4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
bar = foo.reshape(2, 4)
print(bar)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
bar.reshape((4, 2), order='C')

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [10]:
bar.reshape((4, 2), order='F')

array([[1, 3],
       [5, 7],
       [2, 4],
       [6, 8]])

In [11]:
bar.reshape((2, 2, 2), order='C')

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
bar.reshape((2, 2, 2), order='F')

array([[[1, 3],
        [2, 4]],

       [[5, 7],
        [6, 8]]])

In [13]:
bar.reshape(4, -1)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
bar.shape = (4, 2)
print(bar)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [15]:
bar.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [16]:
np.transpose(bar)

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])