# 3.4 NumPy Boolean Indexing

In [2]:
import numpy as np

In [3]:
foo = np.array([
    [3, 9, 7],
    [2, 0, 3],
    [3, 3, 1]
])
print(foo)

[[3 9 7]
 [2 0 3]
 [3 3 1]]


##### Replace every 3 with a 0 in foo

In [4]:
mask = foo == 3
mask

array([[ True, False, False],
       [False, False,  True],
       [ True,  True, False]])

In [5]:
foo[mask]

array([3, 3, 3, 3])

In [6]:
foo[mask] = 0
print(foo)

[[0 9 7]
 [2 0 0]
 [0 0 1]]


In [7]:
rows_1_and_3 = np.array([True, False, True])
cols_2_and_3 = np.array([False, True, True])

In [8]:
foo[rows_1_and_3]

array([[0, 9, 7],
       [0, 0, 1]])

In [9]:
foo[:, cols_2_and_3]

array([[9, 7],
       [0, 0],
       [0, 1]])

In [10]:
foo[rows_1_and_3, cols_2_and_3]

array([9, 1])

In [11]:
names = np.array(["Dennis", "Dee", "Charlie", "Mac", "Frank"])
ages = np.array([43, 44, 43, 42, 74])
genders = np.array(["male", "female", "male", "male", "male"])

##### Who is at least 44?

In [15]:
# Who is at least 44?
ages >= 44
names[ages >= 44]

array(['Dee', 'Frank'], dtype='<U7')

##### Which males are over 42?

In [22]:
# Which males are over 42?
(genders == "male") & (ages > 42)
names[(genders == "male") & (ages > 42)]

array(['Dennis', 'Charlie', 'Frank'], dtype='<U7')

##### And who is not a male or is younger than 43?

In [26]:
# And who is not a male or is younger than 43?
(genders != "male") | (ages < 43)
~(genders == "male") | (ages < 43)
names[(genders != "male") | (ages < 43)]
names[~(genders == "male") | (ages < 43)]

array(['Dee', 'Mac'], dtype='<U7')