# 3.5 NumPy NaN

In [1]:
import numpy as np

In [4]:
bot = np.ones(shape = (3, 4))
print(bot)
bot[[0, 2], [1, 2]] = np.nan
print(bot)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 1. nan  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1. nan  1.]]


In [5]:
bot == np.nan

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [6]:
np.nan == np.nan

False

In [7]:
np.nan != np.nan

True

In [8]:
np.isnan(bot)

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [9]:
foo = np.array([1, 2, 3], dtype = "int32")
foo[1] = np.nan

ValueError: cannot convert float NaN to integer