# 3.6 NumPy Infinity

In [1]:
import numpy as np

In [2]:
np.array([np.inf, np.NINF])

array([ inf, -inf])

In [3]:
np.array([-1, 1]) / 0

/tmp/ipykernel_16761/1273093014.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([-1, 1]) / 0


array([-inf,  inf])

In [4]:
np.inf * 22

inf

In [5]:
np.inf + np.inf

inf

In [6]:
np.inf - np.inf

nan

In [7]:
np.inf / np.inf

nan

In [8]:
np.inf == np.inf

True

In [9]:
np.NINF == np.NINF

True

In [10]:
foo = np.array([4.4, np.inf, 1.0, np.NINF, 3.1, np.inf])

In [11]:
foo == np.inf

array([False,  True, False, False, False,  True])

In [12]:
foo == np.NINF

array([False, False, False,  True, False, False])

In [13]:
np.isposinf(foo)

array([False,  True, False, False, False,  True])

In [14]:
np.isneginf(foo)

array([False, False, False,  True, False, False])

In [15]:
np.isinf(foo)

array([False,  True, False,  True, False,  True])