# 3.7 NumPy Random Module

In [1]:
import numpy as np

In [4]:
np.random.seed(123)

np.random.randint(low = 1, high = 7, size = 3)

array([6, 3, 5])

In [5]:
np.random.seed(2357)

np.random.choice(
    a = np.arange(1, 7), # [1, 2, 3, 4, 5, 6]
    size = 3,
    replace = False,
    p = None
)

array([6, 5, 1])

In [6]:
np.random.choice(
    a = np.arange(1, 7), # [1, 2, 3, 4, 5, 6]
    size = 3,
    replace = False,
    p = np.array([0.1, 0.1, 0.1, 0.1, 0.3, 0.3]) # should equal number of elements and also sum up to 1
)

array([5, 2, 6])

In [7]:
np.random.choice(
    a = np.array(["you", "can", "use", "string", "too"]),
    size = 3,
    replace = False,
    p = None
)

array(['use', 'you', 'can'], dtype='<U6')

In [8]:
foo = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
    [9, 10]
])

In [10]:
np.random.seed(1234)
rand_rows = np.random.randint(
    low = 0,
    high = foo.shape[0],
    size = 3
)
print(rand_rows)

[3 4 4]


In [11]:
foo[rand_rows]

array([[ 7,  8],
       [ 9, 10],
       [ 9, 10]])

##### Without replacement

In [13]:
np.random.seed(1234)
rand_rows2 = np.random.choice(
    a = np.arange(start = 0, stop = foo.shape[0]),
    size = 3,
    replace = False
)
print(rand_rows2)

[4 0 1]


In [14]:
foo[rand_rows2]

array([[ 9, 10],
       [ 1,  2],
       [ 3,  4]])

In [15]:
np.random.permutation(foo) # Only shuffles the rows

array([[ 7,  8],
       [ 5,  6],
       [ 3,  4],
       [ 1,  2],
       [ 9, 10]])

##### Sample from different probability distributions

In [16]:
np.random.uniform(low = 1.0, high = 2.0, size = (2, 2))

array([[1.86066977, 1.15063697],
       [1.19851876, 1.81516293]])

In [17]:
np.random.normal(loc = 0.0, scale = 1.0, size = 2)

array([-0.00867858, -0.32106129])

In [18]:
np.random.binomial(n = 10, p = 0.25, size = (3, 2))

array([[2, 4],
       [1, 0],
       [2, 0]])

## Use newer Random.Generator

In [20]:
generator = np.random.default_rng(seed = 123)

##### Sample three ints between 1 and 6 with replacement

In [21]:
# np.random.randint(low = 1, high = 7, size = 3)
generator.integers(low = 1, high = 7, size = 3)

array([1, 5, 4])

##### Sample three ints between 0 and 9 with replacement

In [22]:
# np.random.choice(a = 10, size = 3, replace = True)
generator.choice(a = 10, size = 3, replace = True)

array([0, 9, 2])

##### Randomly shuffle the rows of a 2d array

In [23]:
# np.random.permutation(foo)
generator.permutation(foo, axis = 0)

array([[ 7,  8],
       [ 9, 10],
       [ 1,  2],
       [ 5,  6],
       [ 3,  4]])

In [24]:
generator.permutation(foo, axis = 1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

##### Randomly sample values from a uniform distribution

In [26]:
# np.random.uniform(low = 1.0, high = 2.0, size = (2, 2))
generator.uniform(low = 1.0, high = 2.0, size = (2, 2))

array([[1.81975456, 1.88989269],
       [1.51297046, 1.2449646 ]])

##### Randomly sample values from a standard distribution

In [27]:
# np.random.normal(loc = 0.0, scale = 1.0, size = 2)
generator.normal(loc = 0.0, scale = 1.0, size = 2)

array([ 1.1921661 , -0.67108968])

##### Randomly sample values from a binomial distribution

In [28]:
# np.random.binomial(n = 10, p = 0.25, size = (3, 2))
generator.binomial(n = 10, p = 0.25, size = (3, 2))

array([[3, 3],
       [5, 1],
       [4, 2]])