## 3.9 Challenge: Professor Prick Problem

You are vindictive, hateful professor and one of your pet peeves is when students rush through their exams. To teach them a lesson, you decide to give 0s to the first three students who score less than sixty, in the order the turned in their exams. So, given a 1d array of integers, identify the first three values less than sixty and replace them with zero.

In [1]:
import numpy as np

In [2]:
generator = np.random.default_rng(80085)
scores = np.round(generator.uniform(low = 30, high = 100, size = 15))

print(scores)

[68. 36. 76. 57. 56. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


In [3]:
scores < 60

array([False,  True, False,  True,  True,  True, False, False,  True,
       False, False, False, False, False,  True])

In [5]:
scores[scores < 60]

array([36., 57., 56., 54., 36., 42.])

In [7]:
selected_first_three = scores[scores < 60][0:3]
print(selected_first_three)

[36. 57. 56.]


In [20]:
new_scores = scores.copy()

[68.  0. 76.  0.  0. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


In [21]:
(new_scores < 60)

array([False,  True, False,  True,  True,  True, False, False,  True,
       False, False, False, False, False,  True])

In [22]:
(new_scores < 60).nonzero()

(array([ 1,  3,  4,  5,  8, 14]),)

In [23]:
(new_scores < 60).nonzero()[0]

array([ 1,  3,  4,  5,  8, 14])

In [24]:
(new_scores < 60).nonzero()[0][:3]

array([1, 3, 4])

In [25]:
new_scores[(new_scores < 60).nonzero()[0][:3]] = 0
print(new_scores)

[68.  0. 76.  0.  0. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]
