# 4.1 Numpy Where

Avoid using `for loop` in NumPy with vectorisation.

In [1]:
import numpy as np

In [27]:
# Make a random number generator
generator = np.random.default_rng()

In [28]:
# Sample 1M integers between 0 and 5
foo = generator.integers(6, size = 2 * 10**6)
print(foo)

[5 0 4 ... 2 4 4]


In [29]:
# Sample 1M integers between 0 and 5
bar = generator.integers(6, size = 2 * 10**6)
print(bar)

[0 4 1 ... 2 5 2]


In [36]:
%%timeit

baz = np.zeros(foo.size)

for i in range(foo.size):
    if bar[i] % 2 == 0:
        baz[i] = foo[i] * 2
    else:
        baz[i] = foo[i] / 2

print(baz)

[10.  0.  2. ...  4.  2.  8.]
[10.  0.  2. ...  4.  2.  8.]
[10.  0.  2. ...  4.  2.  8.]
[10.  0.  2. ...  4.  2.  8.]
[10.  0.  2. ...  4.  2.  8.]
[10.  0.  2. ...  4.  2.  8.]
[10.  0.  2. ...  4.  2.  8.]
[10.  0.  2. ...  4.  2.  8.]
1.5 s ± 130 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [37]:
%%timeit

boz = np.where(bar % 2, foo * 2, foo / 2)

print(boz)

[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8.  ... 1.  8.  2. ]
[2.5 0.  8

In [38]:
np.array_equal(baz, boz)

False