## 4.10 Challenge: Taco Truck

You own a truck that is open 24/7 and you manage five employees who run it. Employees work solo, eight hour shifts. You decide the best way to set their schedule for the upcoming week is to create a bunch of random schedules and select one that looks best.

You build a 1000x21 array of random employee ids where element (i,j) gives the employee id working shift j for schedule i. A schedule is valid as long as no employee works two consecutive shifts. Get the row index of all valid schedules.

In [1]:
import numpy as np

In [3]:
generator = np.random.default_rng(999)
schedules = generator.integers(low = 0, high = 5, size = (1000, 21))

print(schedules)

[[4 3 0 ... 2 0 0]
 [2 4 3 ... 3 3 2]
 [1 0 1 ... 1 2 1]
 ...
 [2 2 1 ... 3 1 4]
 [1 0 3 ... 2 3 2]
 [1 1 4 ... 2 4 2]]


In [9]:
is_valid = np.all(schedules[:, :-1] != schedules[:, 1:], axis = 1) # pick the first 20 elements and compare to the last 20 elements along the rows

np.nonzero(is_valid)[0]

array([ 25, 138, 188, 289, 375, 426, 533, 886, 975, 982])

In [10]:
schedules[:, :-1] != schedules[:, 1:] # 1000 x 20

array([[ True,  True, False, ...,  True,  True, False],
       [ True,  True,  True, ..., False, False,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [False,  True,  True, ..., False,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [False,  True,  True, ...,  True,  True,  True]])

In [11]:
np.all(schedules[:, :-1] != schedules[:, 1:], axis = 1) # check all true; returns a 1d array (1000,)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [13]:
np.nonzero(is_valid) # then pick out all the nonzero elements since False is synonymous with zero - returns a tuple with one element

(array([ 25, 138, 188, 289, 375, 426, 533, 886, 975, 982]),)

In [14]:
np.nonzero(is_valid)[0] # then pick the first element of the tuple

array([ 25, 138, 188, 289, 375, 426, 533, 886, 975, 982])