# 4.2 NumPy Math Functions

In [1]:
import numpy as np

In [2]:
squee = np.array([
    [5.0, 2.0, 9.0,],
    [1.0, 0.0, 2.0,],
    [1.0, 7.0, 8.0,],
])

In [3]:
np.sum(squee)

35.0

In [4]:
np.sum(squee, axis=0)

array([ 7.,  9., 19.])

In [5]:
np.sum(squee, axis=1)

array([16.,  3., 16.])

##### To keep the dimensions of the result array

In [6]:
np.sum(squee, axis=0, keepdims=True)

array([[ 7.,  9., 19.]])

##### With NaN values

In [7]:
squee[0, 0] = np.nan

print(squee)

[[nan  2.  9.]
 [ 1.  0.  2.]
 [ 1.  7.  8.]]


In [8]:
np.sum(squee)

nan

## How to deal with NaN values in data when using Math functions?

### 1. Exclude NaN with where()

In [9]:
np.sum(squee, where = ~np.isnan(squee))

30.0

### 2. Use NaN to num function to replace NaN values with specified number (default is zero).

In [10]:
np.sum(np.nan_to_num(squee))

30.0

### 3. Use the nansum function (it treats NaN as zero)

In [11]:
np.nansum(squee)

30.0