# 4.3 NumPy All and Any Functions

In [2]:
import numpy as np

In [3]:
foo = np.array([
    [np.nan, 4.4],
    [1.0, 3.2],
    [np.nan, np.nan],
    [0.1, np.nan],
])

In [4]:
np.isnan(foo)

array([[ True, False],
       [False, False],
       [ True,  True],
       [False,  True]])

In [5]:
np.any(np.isnan(foo), axis=1)

array([ True, False,  True,  True])

In [9]:
mask_any = np.any(np.isnan(foo), axis=1)

In [10]:
foo[mask_any]

array([[nan, 4.4],
       [nan, nan],
       [0.1, nan]])

In [12]:
mask_all = np.all(np.isnan(foo), axis=1)

print(mask_all)

[False False  True False]


In [13]:
foo[mask_all]

array([[nan, nan]])