# 4.4 NumPy Concatenate

In [1]:
import numpy as np

In [2]:
roux = np.zeros(shape = (3, 2))
print(roux)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [3]:
gumbo = np.zeros(shape = (2, 2))
print(gumbo)

[[0. 0.]
 [0. 0.]]


In [4]:
np.concatenate((roux, roux, roux), axis = 1)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
np.concatenate((roux, gumbo), axis = 0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

To concatenate, the arrays must have the same exact shape, except along the axis on which to concatenate

In [6]:
np.concatenate((roux, gumbo), axis = 1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2