# 4.6 NumPy Sort Function

In [1]:
import numpy as np

In [3]:
foo = np.array([1, 7, 3, 9, 0, 9, 1])
np.sort(foo) # creates a copy before sorting

array([0, 1, 1, 3, 7, 9, 9])

In [4]:
foo.sort() # sorts in place
print(foo)

[0 1 1 3 7 9 9]


In [5]:
bar = np.array([5, np.nan, 3, 11])
np.sort(bar) # NaN are pushed to the end of the array

array([ 3.,  5., 11., nan])

### NumPy does not have an easy way to sort in descending order.

#### Workaround 1 - Sort the array in ascending order and then reverse the result

In [6]:
np.sort(bar)[::-1]

array([nan, 11.,  5.,  3.])

#### Workaround 2 - Negate the array values, sort those in ascending order and then negate that result

In [7]:
~np.sort(~bar) # Does not work on strings

TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [9]:
boo = np.array([
    [55, 10, 12],
    [20, 0, 33],
    [55, 92, 3],
])

In [10]:
np.sort(boo, axis = 0)

array([[20,  0,  3],
       [55, 10, 12],
       [55, 92, 33]])

In [11]:
np.sort(boo, axis = 1)

array([[10, 12, 55],
       [ 0, 20, 33],
       [ 3, 55, 92]])

In [12]:
np.sort(boo, axis = -1)

array([[10, 12, 55],
       [ 0, 20, 33],
       [ 3, 55, 92]])

#### Sort along specific axis based on value in a column or row

In [14]:
print(boo)

[[55 10 12]
 [20  0 33]
 [55 92  3]]


In [15]:
# Sort rows by the first column ascending
boo[np.argsort(boo[:, 0])]

array([[20,  0, 33],
       [55, 10, 12],
       [55, 92,  3]])