## 4.8 Challenge: Movie Ratings

You are given a 10x2 array of floats where each row represents a movie. The first column represents the movie's rating and the second column represents the director's rating. Your goal is to create a third column to represent the overall rating. The overall rating is equal to the movie's rating if it exists, otherwise the director's rating.

In [1]:
import numpy as np

In [3]:
generator = np.random.default_rng(123)
ratings = np.round(generator.uniform(low = 0.0, high = 10.0, size = (10, 2)))
ratings[[1, 2, 7, 9], [0, 0, 0, 0]] = np.nan

print(ratings)

[[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [ 5.  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [nan  5.]]


In [8]:
movie_ratings = np.where(~np.isnan(ratings[:, 0]), ratings[:, 0], ratings[:, 1])
print(movie_ratings)

overall_ratings = np.column_stack((ratings, movie_ratings))

print(overall_ratings)

[7. 2. 8. 9. 8. 5. 8. 6. 9. 5.]
[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [ 5.  2.  5.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [nan  5.  5.]]


In [10]:
# Course solution 1
x1 = np.where(np.isnan(ratings[:, 0]), ratings[:, 1], ratings[:, 0])
result1 = np.insert(arr = ratings, values = x1, axis = 1, obj = 2)

print(result1)

[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [ 5.  2.  5.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [nan  5.  5.]]


In [12]:
# Course solution 2
x2 = np.where(np.isnan(ratings[:, 0]), ratings[:, 1], ratings[:, 0])
result2 = np.hstack((ratings, x2[:, None])) # x2[:, None] converts to a 10x1 array

print(result2)

[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [ 5.  2.  5.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [nan  5.  5.]]
