# 5.1 NumPy Array Indexing - More Detail

In [4]:
import numpy as np

### Mental model for N-dimension arrays

- 1d array - row of values
- 2d array - matrix of values
- 3d array - row of matrices
- 4d array - matrix of matrices

In [8]:
foo = np.arange(3*2*4).reshape((3, 2, 4))
print(foo)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


##### Element (i,j,k) corresponds to ith matrix, jth row and kth column

In [9]:
foo[:, :, 0] # every matrix, every row, 1st column

array([[ 0,  4],
       [ 8, 12],
       [16, 20]])

In [10]:
foo[:, :, [0, 1]] # every matrix, every row, 1st and 2nd column

array([[[ 0,  1],
        [ 4,  5]],

       [[ 8,  9],
        [12, 13]],

       [[16, 17],
        [20, 21]]])

In [12]:
foo2 = np.arange(3*3*4).reshape((3, 3, 4))
print(foo2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


In [13]:
foo2[:, :, 0]

array([[ 0,  4,  8],
       [12, 16, 20],
       [24, 28, 32]])

In [14]:
foo2[:, :, [0, 1]]

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]],

       [[24, 25],
        [28, 29],
        [32, 33]]])

In [16]:
foo

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [17]:
foo[[[0, 2], [2, 0], [1, 1]], [[0, 0], [0, 0], [1, 1]], [[0, 1], [0, 2], [0, 3]]]

array([[ 0, 17],
       [16,  2],
       [12, 15]])

##### Imagine rearranging the above into this
|    |   	   |   |          |   |           |    |
|:---|:-------:|---|:--------:|---|:---------:|---:|
|    | [[0, 2],|   | [[0, 0], |   | [[0, 1],  |    |
|    | [2, 0], |   |  [0, 0], |   |  [0, 2],  |    |
|    | [1, 1]] | , |  [1, 1]] | , |  [0, 3]], |    |
|foo[|         |   |          |   |           |  ] |



|    |   	                  |    |
|---:|:----------------------:|:---|
|   [|[(0, 0, 0) 	(2, 0, 1)]|    |
|    |[(2, 0, 0) 	(0, 0, 2)]|    |
|    |[(1, 1, 0) 	(1, 1, 3)]|]   |


### Mental model output array

When every dimension is indexed with an array and each of those arrays is the same shape, the output array will be the same shape as the index arrays.

In [18]:
idx = np.zeros(shape = (2, 2, 2, 2), dtype = "int32")
result = foo[idx, idx, idx]
result.shape

(2, 2, 2, 2)

In [19]:
foo[ [0, 1], [0, 1], [[0], [1], [2]] ]

array([[ 0, 12],
       [ 1, 13],
       [ 2, 14]])

In [20]:
foo[[0, 0, 2, 2], :, [[0], [1], [2]]]

array([[[ 0,  4],
        [ 0,  4],
        [16, 20],
        [16, 20]],

       [[ 1,  5],
        [ 1,  5],
        [17, 21],
        [17, 21]],

       [[ 2,  6],
        [ 2,  6],
        [18, 22],
        [18, 22]]])

### Mental model indexing with slices

1. Broadcast all index arrays
2. For each slicer
   - Copy each index array N times along a new last axis where N equals the size of the current slicer's dimension
   - Represent the current slicer with an index array

One can leave out some dimension when indexing.

foo[[0, 1]] == foo[[0, 1], :, :]

In [21]:
foo[[0, 1]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [22]:
foo[[0, 1], :, :]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

Scalars have 0 dimension and make the result array scale to the dimensions of the input array.