# 5.2 View Versus Copy

In [1]:
import numpy as np

In [2]:
squid = np.arange(12).reshape(3, -1)
print(squid)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
ward = squid[:, :2] # view of squid array
print(ward)

[[0 1]
 [4 5]
 [8 9]]


In [6]:
sponge = squid[:, [0, 1]] # copy of squid array
print(sponge)

[[0 1]
 [4 5]
 [8 9]]


In [7]:
sponge[0, 0] = 100
print(sponge)
print(squid)

[[100   1]
 [  4   5]
 [  8   9]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
print(ward)

[[0 1]
 [4 5]
 [8 9]]


In [9]:
ward[0, 0] = 100
print(ward)
print(squid)
print(sponge)

[[100   1]
 [  4   5]
 [  8   9]]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[[100   1]
 [  4   5]
 [  8   9]]


In [10]:
squid.__array_interface__

{'data': (23862704, False),
 'strides': None,
 'descr': [('', '<i8')],
 'typestr': '<i8',
 'shape': (3, 4),
 'version': 3}

In [11]:
ward.__array_interface__

{'data': (23862704, False),
 'strides': (32, 8),
 'descr': [('', '<i8')],
 'typestr': '<i8',
 'shape': (3, 2),
 'version': 3}

In [12]:
sponge.__array_interface__

{'data': (29745360, False),
 'strides': (8, 24),
 'descr': [('', '<i8')],
 'typestr': '<i8',
 'shape': (3, 2),
 'version': 3}

In [13]:
np.shares_memory(squid, ward)

True

In [14]:
np.shares_memory(squid, sponge)

False

When one subsets an array using nothing but slices, the result is a view of the original array.

Append .copy() to the end of the statement to force copying

In [15]:
squid[:, :2].copy()

array([[100,   1],
       [  4,   5],
       [  8,   9]])

When one subsets an array using at least one index array, NumPy will automatically copy the data without the risk of overwriting the original array with subsequent operation.