## 5.3 Challenge: Population Verification

You manage a local department for the Census responsible for measuring the population of each block in the city where you live. Even though you could do it yourself, for each of the last five years, you have tasked this job to your subordinate, Jim. What Jim gives you each year is a 5x2x4 array of population estimates called *jim* where (i,j,k) represents Jim's population estimate for block (j,k) in year *i*.

The thing is, you do not fully trust Jim's estimates because you see him spending an ungodly amount of time on Facebook. So, each year, you go behind his back and measure the population of two city blocks. After five years, you have the following data:

- blocks, a 5x2x2 array indicating which blocks you measured each year, where (i,j) gives the coordinates for the *j*th block you measured in year *i*, and
- pops, a corresponding 5x2 array with the population you measured for the *j*th block in year *i*.

How many times was Jim's estimate at least 10% higher or lower than your estimate?

In [1]:
import numpy as np

In [2]:
generator = np.random.default_rng(2357)
jim = np.round(generator.normal(loc = 100, scale = 5, size = (5, 2, 4)))

print(jim)

[[[106. 103.  92. 100.]
  [ 94. 102.  94. 100.]]

 [[104.  96. 109.  96.]
  [101. 104. 102.  92.]]

 [[102. 102. 108. 101.]
  [ 91. 101. 106.  99.]]

 [[101.  98.  95. 102.]
  [100. 101.  99.  93.]]

 [[107. 101. 104. 105.]
  [102.  97. 101. 102.]]]


In [3]:
blocks = np.array([
    [[0, 2], [1, 3]],
    [[1, 2], [0, 0]],
    [[0, 0], [1, 2]],
    [[1, 1], [0, 3]],
    [[0, 1], [1, 0]],
])

In [4]:
pops = np.array([
    [100, 105],
    [110, 92],
    [95, 99],
    [89, 107],
    [101, 98],
])

In [ ]:
error_factor = 0.1

In [5]:
def count_jim_errors(jim, blocks, pops):
    count = 0
    for i in range(5):
        for j in range(2):
            measured_block = blocks[i][j]
            jim_estimate = jim[i][j, pops[i][j]]
            measured_population = pops[i][j]
            if abs(jim_estimate - measured_population) / measured_population >= 0.1:
                count += 1
    return count

In [6]:
def main():
    print(count_jim_errors(jim, blocks, pops))

if __name__ == '__main__':
    main()

IndexError: index 100 is out of bounds for axis 1 with size 4