## 5.5 Challenge: Game of Doors

You are preparing for a game show where you play the following game. You are faced with four doors. Behind one door is cash money, and behind the other three doors is steaming pile of broccoli. If you pick the door with money, you get the option to play again at the risk of losing the money you have collected thus far. If you keep winning, you can play a maximum of three rounds before the game show hosts kick you off the show.

You have some strategy ideas you would like to evaluate before you go on the show. So you hired an unpaid intern to scour through historical recordings of the show and log data on where prizes were located and the value of each prize. Your intern gets back to you with the following matrices:

- prize_doors, a 5x3 array where element (i,j) gives the door hiding the prize in round *j* of the *i*th game, and
- prizes, a 5x3 array where element (i,j) gives the prize amount in round *j* of the *i*th game

Build a 5x3x4 matrix where (i,j,k) represents the prize behind door *k* of round *j* of game *i*.

In [2]:
import numpy as np

In [3]:
prize_doors = np.array([
    [1, 0, 2],
    [0, 0, 1],
    [3, 3, 1],
    [1, 2, 0],
    [2, 1,1 ]
])

In [4]:
prizes = np.array([
    [100, 150, 500],
    [200, 300, 250],
    [150, 100, 325],
    [425, 200, 100],
    [200, 250, 300]
])

In [10]:
""" i = prize_doors[:, None]
print(i)
j = prize_doors[None, :]
print(j)

combo = np.concatenate((i, j, prizes)) """

' i = prize_doors[:, None]\nprint(i)\nj = prize_doors[None, :]\nprint(j)\n\ncombo = np.concatenate((i, j, prizes)) '

In [13]:
answer = np.zeros([5, 3, 4])

"i = [:, None]"
"j = [None, :]"

answer[np.arange(5)[:, None], np.arange(3)[None, :], prize_doors] = prizes

print(answer)

[[[  0. 100.   0.   0.]
  [150.   0.   0.   0.]
  [  0.   0. 500.   0.]]

 [[200.   0.   0.   0.]
  [300.   0.   0.   0.]
  [  0. 250.   0.   0.]]

 [[  0.   0.   0. 150.]
  [  0.   0.   0. 100.]
  [  0. 325.   0.   0.]]

 [[  0. 425.   0.   0.]
  [  0.   0. 200.   0.]
  [100.   0.   0.   0.]]

 [[  0.   0. 200.   0.]
  [  0. 250.   0.   0.]
  [  0. 300.   0.   0.]]]


In [15]:
answer = np.zeros([5, 3, 4])
print(answer)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [16]:
np.arange(5)[:, None]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [17]:
np.arange(3)[None, :]

array([[0, 1, 2]])