## 5.5 Challenge: Peanut Butter

Given <sub>peanut</sub>, a 4x5 array of 0s, and <sub>butter</sub>, a 5-element 1d array of indices, fill the rows of <sub>peanut</sub> with 1s starting down the column indices given by <sub>butter</sub>.

In [2]:
import numpy as np

In [3]:
peanut = np.zeros(shape = (4, 5))
print(peanut)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
butter = np.array([3, 0, 4, 1])
print(butter)

[3 0 4 1]


In [24]:
""" butter2 = butter[np.arange(4)[:, None]]
print(butter2) """

' butter2 = butter[np.arange(4)[:, None]]\nprint(butter2) '

In [25]:
""" peanut[np.arange(4), butter2] """

' peanut[np.arange(4), butter2] '

Build two arrays that match the shape of peanut

In [26]:
# Get corresponding column indices from peanut
col_idxs = np.array([
    [0, 1, 2, 3, 4],
    [0, 1, 2, 3, 4],
    [0, 1, 2, 3, 4],
    [0, 1, 2, 3, 4]
])

Build another 4x5 array of values in butter to associate with each value in peanut

In [27]:
butter_expanded = np.array([
    [3, 3, 3, 3, 3],
    [0, 0, 0, 0, 0],
    [4, 4, 4, 4, 4],
    [1, 1, 1, 1, 1]
])

In [28]:
butter_expanded <= col_idxs

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False,  True],
       [False,  True,  True,  True,  True]])

In [29]:
(butter_expanded <= col_idxs).astype("float64")

array([[0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 1., 1., 1.]])

In [34]:
# Eliminate repetitions
col_idxs2 = np.array([0, 1, 2, 3, 4])

In [35]:
# Eliminate repetitions
butter_expanded2 = np.array([
    [3],
    [0],
    [4],
    [1]
])

In [36]:
butter_expanded2 <= col_idxs2

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False,  True],
       [False,  True,  True,  True,  True]])

In [37]:
(butter_expanded2 <= col_idxs2).astype("float64")

array([[0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 1., 1., 1.]])

Now, we can build the arrays more dynamically

In [43]:
peanut.shape

(4, 5)

In [44]:
# Dynamic generation
col_idxs3 = np.arange(peanut.shape[1])
print(col_idxs3)

[0 1 2 3 4]


In [45]:
butter_expanded3 = butter[:, None]
print(butter_expanded3)

[[3]
 [0]
 [4]
 [1]]


In [46]:
(butter_expanded3 <= col_idxs3).astype("float64")

array([[0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 1., 1., 1.]])

In [47]:
(butter[:, None] <= np.arange(peanut.shape[1])).astype("float64")

array([[0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 1., 1., 1.]])