# 6.1 NumPy Strides

In [1]:
import numpy as np

foo will be stored in contiguous memory blocks

In [2]:
foo = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80]
])

Using int64, each block of memory will be 8 bytes in size. To get to the second element, we have to jump across 16 bytes of data.

foo[1, 1] requires 32 bytes to get to the second row plus another 8 bytes to get to the 2nd element.

In [3]:
foo.strides

(32, 8)

In [6]:
bar = np.lib.stride_tricks.as_strided(
    x = foo,
    shape = (3, 4),
    strides = (16, 8)
)
print(bar)

[[10 20 30 40]
 [30 40 50 60]
 [50 60 70 80]]


In [7]:
bar[1, 0]

30

In [8]:
bar[1, 3]

60

bar is a view of foo. Modifying bar will affect foo also.

In [9]:
bar[1, 0] = 999
print(foo)
print(bar)

[[ 10  20 999  40]
 [ 50  60  70  80]]
[[ 10  20 999  40]
 [999  40  50  60]
 [ 50  60  70  80]]
