# 6.1 NumPy Einstein Sum Function

In [1]:
import numpy as np

In [2]:
A = np.array([0, 1, 2, 3])

B = np.array([4, 5, 6, 7])

In [9]:
""" A = [0 1 2 3]

B = [4 5 6 7] """

' A = [0 1 2 3]\n\nB = [4 5 6 7] '

In [10]:
A = [0, 1, 2, 3]

B = [4, 5, 6, 7]

In [11]:
np.einsum("i, j->i", A, B)

array([ 0, 22, 44, 66])

### Pseudocode

Initialise output as an array of 0s the same size as A

- for each i:
- - for each j:
- - - output[i] += A[i] * B[j]

"i, j->i" means subscript string

- first i - subscript for A axis
- j - subscript for B axis
- ->i - subscript for output axis

Everything is 1d.

In [12]:
np.einsum("i, j->", A, B)

132

### Pseudocode

Initialise output as 0

- for each i:
- - for each j:
- - - output += A[i] * B[j]

Output has 0 dimension

In [13]:
np.einsum("z, z->z", A, B)

array([ 0,  5, 12, 21])

### Pseudocode

Initialise output as an array of 0s the same size as A (and B)

- for each z:
- - output[z] += A[z] * B[z]

Similar to A * B

In [14]:
np.einsum("s, t->st", A, B)

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [ 8, 10, 12, 14],
       [12, 15, 18, 21]])

### Pseudocode

Initialise output as a 4x4 array of 0s

- for each s:
- - for each t:
- - - output[st] += A[s] * B[t]

In [15]:
C = [
    [0, 1],
    [2, 3]
]

D = [
    [4, 5],
    [6, 7]
]

In [16]:
np.einsum("ij, ji ->", C, D)

37

- C has two axes: i and j
- D has two axes: j and i
- output has 0 axis

### Pseudocode

Initialise output as 0

- for each i:
- - for each j:
- - - output += C[ij] * D[ji]

Appears same as: np.sum(C * D.T)

but einsum only visits each element once whereas np.sum(C * D.T) visit each element twice (first when it does the multiplication and second when it does the sum).

np.sum(C * D.T) also creates a temporary array that takes up memory prior to summation.