## 6.3 Challenge: One Hot Encoding

Given an array of integers, one hot encode it into a 2d array.

In [2]:
import numpy as np

In [3]:
yoyoyo = np.array([3, 1, 0, 1])

In [15]:
col_idxs = np.array([0, 1, 2, 3])

In [16]:
yoyoyo_expanded = np.array([
    [3],
    [1],
    [0],
    [1]
])

In [17]:
yoyoyo_expanded == col_idxs

array([[False, False, False,  True],
       [False,  True, False, False],
       [ True, False, False, False],
       [False,  True, False, False]])

In [18]:
(yoyoyo_expanded == col_idxs).astype("float64")

array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [19]:
answer = (yoyoyo_expanded == col_idxs).astype("float64")
print(answer)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


#### Solutions from tutorial

##### Solution 1

In [20]:
num_classes = np.max(yoyoyo) + 1
result = np.eye(num_classes)[yoyoyo]
print(result)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [21]:
num_classes = np.max(yoyoyo) + 1
print(num_classes)

4


In [22]:
np.eye(num_classes) # similar to one-hot encoded for each row

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
# Then pick out rows from the matrix based on 
# values given by yoyoyo
np.eye(num_classes)[yoyoyo]

array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

##### Solution 2

In [27]:
num_cases = len(yoyoyo) # number of rows
num_classes = np.max(yoyoyo) + 1 # number of columns

result2 = np.zeros(shape = (num_cases, num_classes))
# result2[[0, 1, 2, 2], yoyoyo] = 1
result2[np.arange(num_cases), yoyoyo] = 1

print(result2)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
