## 6.4 Challenge: Cumulative Rainfall

Your job is to monitor the rainfall in a region that you have broken into a 3x4 grid. Every time a storm comes, if a cell in the grid gets rain, you record it. At the end of a month, you have the following two arrays of data:
- rain_locations, a 7x2 array representing the location of recorded rainfall, and;
- rain_amounts, a 7-element 1d array representing the amount of rainfall in each corresponding location.

Build a 3x4 array representing the total accumulated rainfall in each cell of the grid.

And do not use a for-loop.

In [2]:
import numpy as np

In [3]:
rain_locations = np.array([
    [2, 3],
    [0, 1],
    [2, 2],
    [2, 3],
    [1, 1],
    [2, 3],
    [1, 1]
])

In [4]:
rain_amounts = np.array([0.5, 1.1, 0.2, 0.9, 1.3, 0.4, 2.0])

In [5]:
np.einsum("z, z->z", rain_locations, rain_amounts)

ValueError: operand has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.

In [20]:
np.einsum("...z, ...z -> z", rain_locations, rain_amounts)

ValueError: output has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.

In [24]:
rainfall = np.zeros((3, 4))
np.add.at(rainfall, (rain_locations[:, 0], rain_locations[:, 1]), rain_amounts)
print(rainfall)

[[0.  1.1 0.  0. ]
 [0.  3.3 0.  0. ]
 [0.  0.  0.2 1.8]]


In [26]:
# Initialise a 3x4 array of 0s
rainfall = np.zeros((3, 4))
print(rainfall)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
# This does not work because of the repeated indices
""" 
rainfall[rain_locations[:, 0], rain_locations[:, 1]] += rain_amounts
print(rainfall)
"""

' \nrainfall[rain_locations[:, 0], rain_locations[:, 1]] = rain_amounts\nprint(rainfall)\n'

NumPy solution for this problem is the numpy.ufunc.at method that exists for all unary functions.

np.add.at(array_to_update, ([indices_of_values_to_update]), corresponding_amount_to_add)