## 6.5 Challenge: Table Tennis

After a series of poor life choices, you find yourself managing a recreational table tennis league. There are 10 participants and in an effort to make the first round of match-ups as exciting as possible, you develop a model that predicts the score difference for every possible pair of players. That is, you produce a 10x10 matrix where (i,j) represents your prediction for player _i_'s score minus player _j_'s score if they were to compete. Given this matrix, determine the "best" match-ups that minimise the sum of squared point differentials.

In [1]:
import numpy as np

In [2]:
generator = np.random.default_rng(0)
score_diffs = np.round(generator.uniform(low=-15, high=15, size=(10, 10)), 2)
np.fill_diagonal(score_diffs, np.nan)
score_diffs[np.triu_indices(10, k=1)] = -score_diffs[np.tril_indices(10, k=-1)]

print(score_diffs)

[[   nan  -9.48  14.15  11.27  -5.65   3.33  10.95  -2.15   5.34  -2.83]
 [  9.48    nan   4.86  -8.61   7.82 -11.29  13.24   4.92   2.86   9.04]
 [-14.15 -11.27    nan  12.28  -2.41   6.04  -5.16  -3.87 -12.81   1.79]
 [  5.65  -3.33 -10.95    nan -13.64   0.     2.24  -3.61  -7.73   0.08]
 [  2.15  -5.34   2.83  -4.86    nan  -0.88  -8.57   2.56  -7.03  -6.33]
 [  8.61  -7.82  11.29 -13.24  -4.92    nan -12.96 -12.82 -14.04  14.56]
 [ -2.86  -9.04 -12.28   2.41  -6.04   5.16    nan -10.91 -14.44 -13.72]
 [  3.87  12.81  -1.79  13.64  -0.    -2.24   3.61    nan  10.54 -14.18]
 [  7.73  -0.08   0.88   8.57  -2.56   7.03   6.33  12.96    nan -11.7 ]
 [ 12.82  14.04 -14.56  10.91  14.44  13.72 -10.54  14.18  11.7     nan]]


In [4]:
np.nanvar(a=score_diffs, axis=0)

array([58.31353333, 79.81028395, 93.61565432, 90.97413333, 60.22504444,
       44.07958765, 81.37335802, 79.5144    , 98.96746914, 90.10388395])

In [5]:
np.nanvar(a=score_diffs, axis=1)

array([ 61.34562222,  61.06434321,  70.23755802,  35.33195556,
        18.10546667, 121.61655062,  44.68143951,  69.10217284,
        48.9328    , 115.98137284])

In [8]:
# Build all permutations of [0, 1, 2, ... 9]
from itertools import permutations
perms = np.array(list(permutations([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])))

# Partition into two matrices representing player 1 and player 2
p1 = perms[:, [0, 2, 4, 6, 8]]
p2 = perms[:, [1, 3, 5, 7, 9]]

# Only retain match-ups where player 1 < player 2
keeps = np.all(p1 < p2, axis=1)
p1 = p1[keeps]
p2 = p2[keeps]

# Build a matrix where (i, j) gives the expected point differential for jth pairing in the ith schedule
point_diffs = score_diffs[p1, p2]

# Calculate sum of squared point differentials
schedules_scores = np.sum(point_diffs**2, axis=1)

# Identify the best schedule
best_idxs = np.argmin(schedules_scores)
best_schedule = np.vstack((p1[best_idxs], p2[best_idxs]))

print(best_schedule)

[[0 3 1 2 4]
 [7 6 8 9 5]]


In [9]:
perms = np.array(list(permutations([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))) # 10! permutations
print(perms)

[[0 1 2 ... 7 8 9]
 [0 1 2 ... 7 9 8]
 [0 1 2 ... 8 7 9]
 ...
 [9 8 7 ... 1 2 0]
 [9 8 7 ... 2 0 1]
 [9 8 7 ... 2 1 0]]


In [10]:
p1 = perms[:, [0, 2, 4, 6, 8]]
print(p1)

[[0 2 4 6 8]
 [0 2 4 6 9]
 [0 2 4 6 7]
 ...
 [9 7 5 3 2]
 [9 7 5 3 0]
 [9 7 5 3 1]]


In [14]:
p2 = perms[:, [1, 3, 5, 7, 9]]
print(p2)

[[1 3 5 7 9]
 [1 3 5 7 8]
 [1 3 5 8 9]
 ...
 [8 6 4 1 0]
 [8 6 4 2 1]
 [8 6 4 2 0]]


In [15]:
keeps = np.all(p1 < p2, axis=1)
print(keeps)

[ True False  True ... False False False]


In [16]:
p1 = p1[keeps] # 10! / 2 unique permutations
print(p1)

[[0 2 4 6 8]
 [0 2 4 6 7]
 [0 2 4 6 7]
 ...
 [8 6 4 1 0]
 [8 6 4 1 0]
 [8 6 4 2 0]]


In [17]:
p2 = p2[keeps]
print(p2)

[[1 3 5 7 9]
 [1 3 5 8 9]
 [1 3 5 9 8]
 ...
 [9 7 5 2 3]
 [9 7 5 3 2]
 [9 7 5 3 1]]


In [18]:
point_diffs = score_diffs[p1, p2]
print(point_diffs)

[[ -9.48  12.28  -0.88 -10.91 -11.7 ]
 [ -9.48  12.28  -0.88 -14.44 -14.18]
 [ -9.48  12.28  -0.88 -13.72  10.54]
 ...
 [-11.7  -10.91  -0.88   4.86  11.27]
 [-11.7  -10.91  -0.88  -8.61  14.15]
 [-11.7  -10.91  -0.88  12.28  -9.48]]


In [19]:
schedules_scores = np.sum(point_diffs**2, axis=1) # along the columns
print(schedules_scores)

[497.3613 651.0292 540.7732 ... 407.325  531.0471 497.3613]


In [20]:
best_idxs = np.argmin(schedules_scores)
print(best_idxs)

16490


In [21]:
# Player top vs player bottom
best_schedule = np.vstack((p1[best_idxs], p2[best_idxs]))
print(best_schedule)

[[0 3 1 2 4]
 [7 6 8 9 5]]
