## 6.6 Challenge: Where is Waldo

Given a 1-million element array where each element is a random character in a-z, identify the starting index of every sequence that spells 'waldo'.

**Twist** - include sequences where 4 of the 5 characters match (e.g. 'wafdo' and 'xaldo' but not 'wadlo').

In [8]:
import numpy as np
import string

In [9]:
generator = np.random.default_rng(123)
chars = generator.choice(list(string.ascii_lowercase), size=10**6, replace=True)

print(chars[:20])

['a' 'r' 'p' 'b' 'x' 'f' 'g' 'e' 'i' 'e' 'j' 'v' 'l' 'y' 'l' 'h' 'u' 'v'
 'w' 'x']


In [26]:
waldo = np.array(["w", "a", "l", "d", "o"], dtype="<U1")

In [27]:
np.chararray.find(chars, waldo)

ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (1000000,) and arg 1 with shape (5,).

In [ ]:
np.chararray.find(chars, "waldo")

array([-1, -1, -1, ..., -1, -1, -1])

In [31]:
windows = np.lib.stride_tricks.as_strided(
    x = chars,
    shape = (len(chars) - (5-1), 5),
    strides = (chars.strides[0], chars.strides[0])
)
waldo = np.array(["w", "a", "l", "d", "o"], dtype="<U1")
start_idxs = np.where((windows == waldo).sum(axis=1) >= 4)[0]
print(start_idxs)

[ 15063 142002 154213 177190 330101 335422 348645 415541 447457 505677
 669313 673093 726243 879558 946156]


In [32]:
# Five character sequences from the chars array
print(windows)

[['a' 'r' 'p' 'b' 'x']
 ['r' 'p' 'b' 'x' 'f']
 ['p' 'b' 'x' 'f' 'g']
 ...
 ['y' 'a' 'b' 'o' 'k']
 ['a' 'b' 'o' 'k' 'a']
 ['b' 'o' 'k' 'a' 'z']]


In [33]:
print(waldo)

['w' 'a' 'l' 'd' 'o']


In [34]:
windows == waldo

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       ...,
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [36]:
# Interested in rows where at least four values are True
np.where((windows == waldo).sum(axis=1) >= 4)

(array([ 15063, 142002, 154213, 177190, 330101, 335422, 348645, 415541,
        447457, 505677, 669313, 673093, 726243, 879558, 946156]),)

In [37]:
# Only want the first element of the above tuple
np.where((windows == waldo).sum(axis=1) >= 4)[0]

array([ 15063, 142002, 154213, 177190, 330101, 335422, 348645, 415541,
       447457, 505677, 669313, 673093, 726243, 879558, 946156])

##### Validation

In [38]:
for idx in start_idxs:
    print("".join(chars[idx:(idx + 5)]))

waldl
walio
walfo
waudo
walmo
wardo
wtldo
faldo
zaldo
wpldo
waldd
wxldo
qaldo
wakdo
kaldo
