## 6.7 Challenge: Outer Product

Calculate the element-wise outer product of two matrices, A and B.

In [2]:
import numpy as np

In [4]:
A = np.arange(10*3).reshape((10,3))
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


In [5]:
B = np.arange(10*5).reshape((10,5))
print(B)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [6]:
np.outer(A, B)

array([[   0,    0,    0, ...,    0,    0,    0],
       [   0,    1,    2, ...,   47,   48,   49],
       [   0,    2,    4, ...,   94,   96,   98],
       ...,
       [   0,   27,   54, ..., 1269, 1296, 1323],
       [   0,   28,   56, ..., 1316, 1344, 1372],
       [   0,   29,   58, ..., 1363, 1392, 1421]])

In [8]:
np.multiply.outer(A, B)

array([[[[   0,    0,    0,    0,    0],
         [   0,    0,    0,    0,    0],
         [   0,    0,    0,    0,    0],
         ...,
         [   0,    0,    0,    0,    0],
         [   0,    0,    0,    0,    0],
         [   0,    0,    0,    0,    0]],

        [[   0,    1,    2,    3,    4],
         [   5,    6,    7,    8,    9],
         [  10,   11,   12,   13,   14],
         ...,
         [  35,   36,   37,   38,   39],
         [  40,   41,   42,   43,   44],
         [  45,   46,   47,   48,   49]],

        [[   0,    2,    4,    6,    8],
         [  10,   12,   14,   16,   18],
         [  20,   22,   24,   26,   28],
         ...,
         [  70,   72,   74,   76,   78],
         [  80,   82,   84,   86,   88],
         [  90,   92,   94,   96,   98]]],


       [[[   0,    3,    6,    9,   12],
         [  15,   18,   21,   24,   27],
         [  30,   33,   36,   39,   42],
         ...,
         [ 105,  108,  111,  114,  117],
         [ 120,  123,  126,  129, 

In [14]:
def outer_prod_broadcasting(A, B):
    """ Broadcasting trick """
    # return A[:,:, None] * B[:, None]
    return A[..., None] * B[:, None]
    # A (10,3) -> (10, 3, 1)
    # B (10,5) -> (10, 1, 5)

In [15]:
def outer_prod_einsum(A, B):
    """ einsum trick """
    return np.einsum("ij,ik->ijk", A, B)

    # Initialise output as an array of 0s with shape (10, 3, 5)
    # for i:
    #   for j:
    #      for k:
    #        output_ijk += A_ij * B_ik

In [16]:
# Reshape both A and B arrays to match the output array shape
# Then output_ijk = A_ijk * B_ijk
def outer_prod_stride(A, B):
    """ stride trick """
    a = A.shape[-1]
    b = B.shape[-1]
    d = A.strides[-1]
    new_shape = A.shape + (b,)
    As = np.lib.stride_tricks.as_strided(A, shape=new_shape, strides=(a*d, d, 0))
    Bs = np.lib.stride_tricks.as_strided(B, shape=new_shape, strides=(b*d, d, 0))
    return As * Bs

In [17]:
%timeit op1 = outer_prod_broadcasting(A, B)

5.05 µs ± 1.39 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [18]:
%timeit op2 = outer_prod_einsum(A, B)

6.01 µs ± 932 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [19]:
%timeit op3 = outer_prod_stride(A, B)

21.5 µs ± 1.07 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
